# Generated by Django 5.0.4 on 2024-05-26 07:16

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('user_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('course_id', models.CharField(blank=True, default='0', max_length=15)),
                ('year_id', models.CharField(blank=True, default='0', max_length=10)),
                ('sem', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('even', 'Even'), ('odd', 'Odd'), ('passed out', 'Passed Out')], default='0', max_length=10, null=True)),
                ('language_pref', models.CharField(blank=True, choices=[('0', '0'), ('hindi', 'Hindi'), ('kannada', 'Kannada'), ('malayalam', 'Malayalam')], default='0', max_length=10, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('0', '0'), ('normal', 'Normal'), ('ai/ml', 'AI/ML and Big Data'), ('logistics', 'Supply Chain & Logistics'), ('aviation', 'Hospitality & Aviation')], default='0', max_length=100, null=True)),
                ('lab_batch_type', models.CharField(blank=True, choices=[('0', '0'), ('normal', 'Normal'), ('addon', 'AddOn')], default='0', max_length=10, null=True)),
                ('section_id', models.CharField(blank=True, choices=[('0', '0'), ('A', 'A'), ('B', 'B')], default='0', max_length=1, null=True)),
                ('AdmissionYear', models.PositiveIntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'CustomUsers',
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
