# Generated by Django 5.0.4 on 2024-05-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=15, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('total_classes', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(default='0', max_length=10, null=True)),
                ('subject_type', models.CharField(choices=[('normal theory', 'Normal Theory'), ('normal lab', 'Normal Lab'), ('ai/ml lab', 'Ai/Ml Lab'), ('ai/ml theory', 'Ai/Ml Theory'), ('logistics', 'Supply Chain & Logistics'), ('aviation', 'Aviation & Hospitality'), ('hindi', 'Hindi'), ('kannada', 'Kannada')], max_length=100)),
                ('sem', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('lab_batch_type', models.CharField(choices=[('0', '0'), ('addon', 'Addon'), ('normal', 'Normal')], default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('year_name', models.CharField(max_length=15)),
            ],
        ),
    ]
